---
title: "Backlink Analysis"
output: 
  flexdashboard::flex_dashboard:
    theme:
      bg: "#FFFFFF"
      fg: "#000437" 
      primary: "#9e0b37"
      base_font:
        google: Prompt
      code_font:
        google: JetBrains Mono
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
```

```{r, include=FALSE}
library(tidyverse)
library(readxl)
library(here)
library(knitr)
library(kableExtra)
library(plotly)
```


```{r, echo=FALSE}
## ---- readdata
pdn <- readxl::read_xlsx(here("data-raw", 
                              "2022-08-17_07-19_new-explorer-backlinks_fresh_domain_pdn-ac-lk.xlsx"))

cmb <- readxl::read_xlsx(here("data-raw", 
                              "2022-08-17_07-20_new-explorer-backlinks_fresh_domain_cmb-ac-lk.xlsx"))
sjp <- readxl::read_xlsx(here("data-raw", 
                              "2022-08-17_07-20_new-explorer-backlinks_fresh_domain_sjp-ac-lk.xlsx"))

kdu <- readxl::read_xlsx(here("data-raw", 
                              "2022-08-17_07-21_new-explorer-backlinks_fresh_domain_kdu-ac-lk.xlsx"))


kln <- readxl::read_xlsx(here("data-raw", 
                              "2022-08-17_07-21_new-explorer-backlinks_fresh_domain_kln-ac-lk.xlsx"))

sliit <- readxl::read_xlsx(here("data-raw", 
                              "2022-08-17_07-21_new-explorer-backlinks_fresh_domain_sliit-lk.xlsx"))

```

# Overview

Column {data-width=650}
-----------------------------------------------------------------------

### Total number of unique target links


```{r, echo=FALSE}
sjpc <- length(unique(sjp$`Target URL`))
cmbc <- length(unique(cmb$`Target URL`))
kduc <- length(unique(kdu$`Target URL`))
klnc <- length(unique(kln$`Target URL`))
pdnc <- length(unique(pdn$`Target URL`))
sliitc <- length(unique(sliit$`Target URL`))

tu <- data.frame(University=c("SJP", "CMB", "KDU", "KLN", "PDN", "SLIIT"), Count = c(sjpc, cmbc, kduc, klnc, pdnc, sliitc))

p1 <- ggplot(tu,aes(x= reorder(University,Count),Count))+geom_bar(stat ="identity") + coord_flip() + geom_text(aes(label = signif(Count)), nudge_y = 35) + xlab("University Code") +ylab("Count") 
p1
```


Column {data-width=650}
-----------------------------------------------------------------------

### Number of unique source links/ domains

```{r, echo=FALSE}
sjps <- length(unique(sjp$`Source URL`))
cmbs <- length(unique(cmb$`Source URL`))
kdus <- length(unique(kdu$`Source URL`))
klns <- length(unique(kln$`Source URL`))
pdns <- length(unique(pdn$`Source URL`))
sliits <- length(unique(sliit$`Source URL`))

su <- data.frame(University=c("SJP", "CMB", "KDU", "KLN", "PDN", "SLIIT"), Count = c(sjps, cmbs, kdus, klns, pdns, sliits))

p2 <- ggplot(su,aes(x= reorder(University,Count),Count))+geom_bar(stat ="identity") + coord_flip() + geom_text(aes(label = signif(Count)), nudge_y = 50) + xlab("University Code") +ylab("Count")
p2
```

# Source Link (Trust and Ciations Flow)

# 2

Column {data-width=650 .tabset}
-----------------------------------------------------------------------

### Total number of unique source links


```{r, echo=FALSE}
sjpc <- length(unique(sjp$`Target URL`))
cmbc <- length(unique(cmb$`Target URL`))
kduc <- length(unique(kdu$`Target URL`))
klnc <- length(unique(kln$`Target URL`))
pdnc <- length(unique(pdn$`Target URL`))
sliitc <- length(unique(sliit$`Target URL`))

tu <- data.frame(University=c("SJP", "CMB", "KDU", "KLN", "PDN", "SLIIT"), Count = c(sjpc, cmbc, kduc, klnc, pdnc, sliitc))

ggplot(tu,aes(x= reorder(University,Count),Count))+geom_bar(stat ="identity") + coord_flip() + geom_text(aes(label = signif(Count)), nudge_y = 35) + xlab("University Code") +ylab("Count")
```


### Chart B

```{r}

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart C

```{r}

```

### Chart D

```{r}

```

# 2